### ISSUE TITLE
When submitting an invalid parameter, no error is returned

### ISSUE THREAD

**Issue by vladbalan** [SabreDevStudio/sabre-dev-studio-node#11]
I am using this code inside a server file of a meteor app:
```js
const SabreDevStudio = require('sabre-dev-studio');
const sabreDevStudio = new SabreDevStudio({
  client_id: 'my:client:id',
  client_secret: 'mysecret',
  uri: 'https://api.test.sabre.com',
});

const options = {
  origin: 'somewrongcode', // Some wrong code, should return 404
  grant_type: 'client_credentials',
  earliestdeparturedate: '2016-10-01',
  latestdeparturedate: '2016-10-03',
  lengthofstay: '7',
  pointofsalecountry: 'US',
};

sabreDevStudio.get('/v2/shop/flights/fares', options, (error, result) => {
  if (err) {
    console.log('error: ', error);
  } else {
    console.log('result: ', result);
  }
});
```
If I use `JFK` as my `origin` parameter, I get a result and it gets printed to the console. But if I submit an invalid code e.g. `somewrongcode`, I get neither `error` nor `result`.

Using the same parameters at https://developer.sabre.com/io-docs I get this response:
```json
{
    "status": "Complete",
    "type": "Application",
    "errorCode": "WARN.RAF.APPLICATION",
    "timeStamp": "2016-09-15T10:24:33+00:00",
    "message": "No results were found"
}
```
with the status `404 Not Found`.

**Comment by barrettclark** [comment]
Thank you for the bug report. I've recently accepted a PR from someone that cleaned up the response a little, and I think that may have also resolved this issue.

I ran this code given your options:

```javascript
sabreDevStudio.get('/v2/shop/flights/fares', options, (error, result) => {
  console.log("Error:", error, "\nResult:", result); 
});
```

And I got the following output:

```
Error: { Error: NotFound
Result: {"status":"Complete","type":"Application","errorCode":"WARN.RAF.APPLICATION","timeStamp":"2016-09-26T17:16:37+00:00","message":"No results were found"}
```

Can you update to `sabre-dev-studio@1.2.0` and let me know if it solves your need?

**Comment by vladbalan** [comment]
Updating do `sabre-dev-studio@1.2.0` fixes this issue! Thank you!

**Comment by barrettclark** [comment]
That's great! Thank you.

**Comment by churromorales20** [comment]
Im new i Sabre how may i update to sabre-dev-studio@1.2.0 ??? Im working in a simple REST client for php
