### ISSUE TITLE
AirTicketRQ REST end point

### ISSUE THREAD

**Issue by joshua1** [SabreDevStudio/sabre-dev-studio-node#15]
Hi,
I wish to know when if ever , a REST end point for issuing tickets (AirTicketRQ) will be implemented to match the SOAP API, having come all the way from flight search , to payments (another system) it will be ideal to have this also in REST instead of having to do a SOAP implementation

**Comment by jmacagno** [comment]
Yes Joshua, there is plans to release a Beta version soon of the same service.

**Comment by joshua1** [comment]
That will be great. will keep looking out
