### ISSUE TITLE
fatal error: too many errors emitted, stopping now [-ferror-limit=]

### ISSUE THREAD

**Issue by nyjy85** [SabreDevStudio/sabre-dev-studio-node#6]
I keep getting the following errors when I try to npm install it:

20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joanne/apps/sabre/node_modules/sabre-dev-studio/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing dtrace-provider@0.2.8

**Comment by barrettclark** [comment]
I think it was as simple as updating the dependencies:

```
> dtrace-provider@0.5.0 install /Users/barrettclark/Desktop/node_modules/sabre-dev-studio/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map
sabre-dev-studio@1.0.2 node_modules/sabre-dev-studio
├── oauth@0.9.13
├── simple-errors@1.0.1 (errno@0.1.3)
└── bunyan@1.4.0 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.5.0)
```

Can you confirm that it works for you?

**Comment by barrettclark** [comment]
Marking as closed.
